name: 'Send Discord Message'
description: 'Sends a message to a Discord channel via webhook'
inputs:
  summary:
    description: 'The summary message to send'
    required: true
runs:
  using: 'python'
  main: 'send_discord_message.py'

