# .github/workflows/cleanup.yml
name: Cleanup

on:
  workflow_run:
    workflows: ["Upload to FTP"]
    types:
      - completed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: rm -rf temp_upload/

