# .github/workflows/get_changed_files.yml
name: Get Changed Files

on:
  workflow_run:
    workflows: ["Checkout Code"]
    types:
      - completed

jobs:
  get_files:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        id: get_changed_files
        run: |
          files=$(git diff --name-only ${{ github.event.workflow_run.head_commit.id }}^ ${{ github.event.workflow_run.head_commit.id }})
          echo "files=${files}" >> $GITHUB_ENV
