name: Global Health Check for Nitrado API

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes

jobs:
  health_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Health Check Script
        env:
          API_KEY: ${{ secrets.NITRADO_TOKEN }}  # Use the correct secret name
        run: |
          python -c "
import requests
import os

class NitradoAPI:
    def __init__(self, api_key):
        self.api_key = api_key
        self.base_url = 'https://api.nitrado.net'

    def _get_headers(self):
        return {
            'Authorization': f'Bearer {self.api_key}',
            'Content-Type': 'application/json'
        }

    def health_check(self):
        response = requests.get(f'{self.base_url}/services', headers=self._get_headers())
        return response.status_code == 200

api = NitradoAPI(os.environ['API_KEY'])
if api.health_check():
    print('API is healthy.')
else:
    print('API is not healthy.')
            "
