name: Kitty Linter

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    name: Kitty Linter
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Get changed files
        id: get_changed_files
        run: |
          files=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files: $files"  # Debugging line
          if [ -z "$files" ]; then
            echo "No changed files detected. Exiting."
            echo "files=" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "files=$(echo "$files" | tr '\n' ' ')" >> $GITHUB_OUTPUT
          fi

      - name: Install Prettier and XML Plugin
        run: |
          npm install --save-dev prettier @prettier/plugin-xml || { echo "Failed to install Prettier"; exit 1; }

      - name: Format files with Prettier
        run: |
          IFS=' ' read -r -a files <<< "${{ steps.get_changed_files.outputs.files }}"
          for file in "${files[@]}"; do
            echo "Processing file: $file"  # Debugging line
            if [ -f "$file" ]; then
              case "$file" in
                *.xml)
                  npx prettier --write "$file" --parser xml || { echo "Failed to format $file"; exit 1; }
                  ;;
                *.json)
                  npx prettier --write "$file" --parser json || { echo "Failed to format $file"; exit 1; }
                  ;;
                *.yaml|*.yml)
                  npx prettier --write "$file" --parser yaml || { echo "Failed to format $file"; exit 1; }
                  ;;
                *)
                  echo "Skipping $file (not an XML, JSON, or YAML file)"
                  ;;
              esac
            else
              echo "$file does not exist."
            fi
          done

      - name: Run Super Linter
        id: linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_LOCAL: false
          DEFAULT_BRANCH: main
          DISABLE_LINTING: "false"
          ENABLE_LINTER: "eslint,LibXML"
          VALIDATE_XML: "true"
          VALIDATE_JSON: "true"

      - name: Commit formatted changes
        run: |
          git config --local user.email "74373243+Kitty-Shackleford@users.noreply.github.com"
          git config --local user.name "Kitty-Shackleford"
          git add .
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Format files with Prettier" || echo "Commit failed"
          else
            echo "No changes to commit"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          repository: Kitty-Shackleford/tsb
          force_with_lease: true

      - name: Create temporary directory
        run: mkdir temp_upload

      - name: Copy files for FTP upload
        run: |
          echo "Changed files to copy: ${{ steps.get_changed_files.outputs.files }}"  # Debugging line
          for file in ${{ steps.get_changed_files.outputs.files }}; do
            echo "Checking file: $file"  # Debugging line
            if [[ "$file" =~ ^(dayzOffline\.sakhal|dayzOffline\.enoch|dayzOffline\.chernarusplus) ]]; then
              cp "$file" temp_upload/ || { echo "Failed to copy $file"; exit 1; }
              echo "Copied $file to temp_upload/"  # Debugging line
            else
              echo "Skipping $file (not in specified directories)"
            fi
          done

      - name: Check for files to upload
        run: |
          echo "Files in temp_upload before upload: $(ls -A temp_upload/)"  # Debugging line
          if [ -z "$(ls -A temp_upload/)" ]; then
            echo "No files to upload. Exiting."
            exit 0
          fi

      - name: Upload to FTP
        if: success()
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: temp_upload/
          server-dir: /dayzxb_missions/

      - name: Clean up
        run: rm -rf temp_upload/
