# .github/workflows/run_linter.yml
name: Run Linter

on:
  workflow_run:
    workflows: ["Get Changed Files"]
    types:
      - completed

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super Linter
        id: linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_LOCAL: false
          DEFAULT_BRANCH: main
          DISABLE_LINTING: "false"
          ENABLE_LINTER: "eslint,LibXML"
          VALIDATE_XML: "true"
          VALIDATE_JSON: "true"
        with:
          FILES: ${{ env.files }}
