name: Send Discord Message

on:
  workflow_call:
    inputs:
      summary:
        required: true
        type: string

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send summary to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "content": "${{ inputs.summary }}"
          }' $DISCORD_WEBHOOK
