name: NitrAPI Check Gameserver Details

on:
  workflow_dispatch: {}  # Manual trigger
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes

jobs:
  check_gameserver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Gameserver Details Check
        id: gameserver_check
        env:
          NITRADO_TOKEN: ${{ secrets.NITRADO_TOKEN }}  # Your API key
          NITRADO_ID: ${{ secrets.NITRADO_ID }}  # Your Nitrado Server ID
        run: |
          python gameserver_check.py > output.md
          echo "## Summary of Gameserver Details" >> $GITHUB_STEP_SUMMARY
          cat output.md >> $GITHUB_STEP_SUMMARY
          echo "summary<<EOF" >> $GITHUB_ENV
          cat output.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Display Summary
        run: cat $GITHUB_STEP_SUMMARY

      - name: Trigger Discord Message Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: send_discord_message.yml
          inputs:
            summary: ${{ env.summary || 'No summary available.' }}  # Use env for the summary


  
