name: Send Discord Message

on:
  workflow_dispatch:  # Manual trigger for this workflow
  workflow_run:  # Triggered by another workflow completion
    workflows: ["NitrAPI Check Gameserver Details"]
    types:
      - completed

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Message
        run: |
          node send_discord_message.js "${{ github.event.inputs.summary }}"
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}  # Set the webhook URL from secrets
