name: 'Send Discord Message'
description: 'Sends a message to a Discord channel via webhook'

on:
  workflow_dispatch:  # Manual trigger for this workflow
  workflow_run:  # Triggered by another workflow completion
    workflows: ["NitrAPI Check Gameserver Details"]  # Ensure this matches the name of your main workflow
    types:
      - completed

inputs:
  summary:
    description: 'The summary message to send'
    required: true

runs:
  using: 'node16'  # or node12, node20
  main: 'send_discord_message.js'


