# .github/workflows/upload_to_ftp.yml
name: Upload to FTP

on:
  workflow_run:
    workflows: ["Run Linter"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create temporary directory
        run: mkdir temp_upload

      - name: Copy changed files
        run: |
          for file in ${{ env.files }}; do
            cp "$file" temp_upload/ || echo "Failed to copy $file"
          done

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: temp_upload/
          server-dir: /dayzxb_missions/  # Adjust as necessary

      - name: Clean up
        run: rm -rf temp_upload/
